name: CI

# Controls when the action will run. Triggers the workflow on push for any branch, and
# pull requests to master
on:
  push:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    strategy:
      matrix:
      # current ccl-bin has a flaky zip file, so roswell can't install it.
      # Specify a version that works for now.
        lisp: [sbcl-bin, ccl-bin/1.12]
        os: [  ubuntu-latest, macos-latest]

    # run the job on every combination of "lisp" and "os" above
    runs-on: ${{ matrix.os }}

    # default to msys2 shell on windows, since roswell install-for-ci.sh tries to install using pacman
    defaults:
      run:
        shell: ${{ fromJSON('[ "bash", "msys2 {0}" ]') [ matrix.os == 'windows-latest' ] }}

  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run tests  
        run: |
          cd ${{ github.workspace }}/src; pwd; ls ..; \
          sbcl --version;
      - run: echo "🍏 This job's status is ${{ job.status }}."
